# Generated by Django 4.0.6 on 2022-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackJob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Submitted_Date',
            field=models.TextField(default='sss'),
        ),
        migrations.AddField(
            model_name='job',
            name='applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_title',
            field=models.CharField(max_length=120),
        ),
    ]
