# Generated by Django 4.0.3 on 2022-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackJob', '0002_job_submitted_date_job_applied_alter_job_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='RequiredSkills',
            field=models.TextField(default='sss'),
        ),
        migrations.AddField(
            model_name='job',
            name='TakehomePoint',
            field=models.TextField(null=True),
        ),
    ]
