# Generated by Django 4.0.3 on 2022-07-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackJob', '0006_alter_job_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Submitted_Date',
            field=models.DateField(),
        ),
    ]
