# Generated by Django 4.0.3 on 2022-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackJob', '0007_alter_job_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Submitted_Date',
            field=models.TextField(),
        ),
    ]
